-- Database Schema for Hospital Management System

CREATE DATABASE IF NOT EXISTS hospital_db;
USE hospital_db;

-- Module 1: Security & Admin
CREATE TABLE IF NOT EXISTS User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role ENUM('Admin', 'Doctor', 'Nurse', 'Patient', 'Staff', 'Receptionist', 'LabTech', 'Lab Technician') DEFAULT 'Staff',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Role (
    RoleID INT AUTO_INCREMENT PRIMARY KEY,
    RoleName VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Permission (
    PermissionID INT AUTO_INCREMENT PRIMARY KEY,
    ActionName VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Role_Permission (
    RolePermissionID INT AUTO_INCREMENT PRIMARY KEY,
    RoleID INT NOT NULL,
    PermissionID INT NOT NULL,
    FOREIGN KEY (RoleID) REFERENCES Role(RoleID) ON DELETE CASCADE,
    FOREIGN KEY (PermissionID) REFERENCES Permission(PermissionID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Department (
    DepartmentID INT AUTO_INCREMENT PRIMARY KEY,
    DepartmentName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Staff (
    StaffID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT UNIQUE NOT NULL,
    DepartmentID INT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Audit_Log (
    LogID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ActionDescription TEXT NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

-- Module 2: Patient & Logistics
CREATE TABLE IF NOT EXISTS Patient (
    PatientID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT UNIQUE,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Visit (
    VisitID INT AUTO_INCREMENT PRIMARY KEY,
    PatientID INT NOT NULL,
    AdmissionTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    VisitType ENUM('Inpatient', 'Emergency', 'Outpatient') NOT NULL,
    FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Appointment (
    AppointmentID INT AUTO_INCREMENT PRIMARY KEY,
    PatientID INT NOT NULL,
    StaffID INT NOT NULL,
    AppointmentTime DATETIME NOT NULL,
    Status ENUM('Scheduled', 'Completed', 'Cancelled') DEFAULT 'Scheduled',
    FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Bed (
    BedID INT AUTO_INCREMENT PRIMARY KEY,
    RoomNumber VARCHAR(20) NOT NULL,
    IsAvailable BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS Bed_Assignment (
    BedAssignID INT AUTO_INCREMENT PRIMARY KEY,
    PatientID INT NOT NULL,
    BedID INT NOT NULL,
    VisitID INT NOT NULL,
    StartTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    EndTime DATETIME,
    FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE,
    FOREIGN KEY (BedID) REFERENCES Bed(BedID) ON DELETE CASCADE,
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Operation_Room (
    OpRoomID INT AUTO_INCREMENT PRIMARY KEY,
    RoomName VARCHAR(50) NOT NULL,
    IsAvailable BOOLEAN DEFAULT TRUE
);

-- Module 3: Doctor & EMR
CREATE TABLE IF NOT EXISTS Diagnosis (
    DiagnosisID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    StaffID INT NOT NULL,
    DiagnosisNotes TEXT NOT NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Treatment_Plan (
    PlanID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    StaffID INT NOT NULL,
    PlanDetails TEXT NOT NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Surgery_Request (
    RequestID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    RequestingStaffID INT NOT NULL,
    SurgeonStaffID INT,
    OpRoomID INT,
    ScheduledTime DATETIME,
    Status ENUM('Pending', 'In Progress', 'Completed', 'Cancelled') DEFAULT 'Pending',
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE,
    FOREIGN KEY (RequestingStaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE,
    FOREIGN KEY (SurgeonStaffID) REFERENCES Staff(StaffID) ON DELETE SET NULL,
    FOREIGN KEY (OpRoomID) REFERENCES Operation_Room(OpRoomID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Surgery_Report (
    ReportID INT AUTO_INCREMENT PRIMARY KEY,
    RequestID INT UNIQUE NOT NULL,
    ReportText TEXT NOT NULL,
    FOREIGN KEY (RequestID) REFERENCES Surgery_Request(RequestID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Doctor_Notes (
    NoteID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    StaffID INT NOT NULL,
    NoteText TEXT NOT NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

-- Module 4: Nurse & Staffing
CREATE TABLE IF NOT EXISTS Shift (
    ShiftID INT AUTO_INCREMENT PRIMARY KEY,
    ShiftName VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Attendance (
    AttendanceID INT AUTO_INCREMENT PRIMARY KEY,
    ShiftID INT NOT NULL,
    StaffID INT NOT NULL,
    ClockInTime DATETIME NOT NULL,
    ClockOutTime DATETIME,
    FOREIGN KEY (ShiftID) REFERENCES Shift(ShiftID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Nurse_Assignment (
    NurseAssignID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    StaffID INT NOT NULL,
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Nurse_Task (
    TaskID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    AssignedStaffID INT NOT NULL,
    Description TEXT NOT NULL,
    Status ENUM('Pending', 'Completed') DEFAULT 'Pending',
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE,
    FOREIGN KEY (AssignedStaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Operation_Assignment (
    OpAssignID INT AUTO_INCREMENT PRIMARY KEY,
    RequestID INT NOT NULL,
    StaffID INT NOT NULL,
    Role VARCHAR(50) NOT NULL,
    FOREIGN KEY (RequestID) REFERENCES Surgery_Request(RequestID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

-- Module 5: Lab & Prescriptions
CREATE TABLE IF NOT EXISTS Test_Type (
    TestTypeID INT AUTO_INCREMENT PRIMARY KEY,
    TestName VARCHAR(100) NOT NULL,
    ReferenceRange VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Lab_Order (
    OrderID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    RequestingStaffID INT NOT NULL,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE,
    FOREIGN KEY (RequestingStaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Lab_Test (
    TestID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT NOT NULL,
    TestTypeID INT NOT NULL,
    Status ENUM('Pending', 'Completed', 'Cancelled') DEFAULT 'Pending',
    FOREIGN KEY (OrderID) REFERENCES Lab_Order(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (TestTypeID) REFERENCES Test_Type(TestTypeID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Lab_Device (
    DeviceID INT AUTO_INCREMENT PRIMARY KEY,
    DeviceName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Lab_Result (
    ResultID INT AUTO_INCREMENT PRIMARY KEY,
    TestID INT UNIQUE NOT NULL,
    DeviceID INT,
    ResultValue TEXT NOT NULL,
    FOREIGN KEY (TestID) REFERENCES Lab_Test(TestID) ON DELETE CASCADE,
    FOREIGN KEY (DeviceID) REFERENCES Lab_Device(DeviceID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Lab_Result_File (
    FileID INT AUTO_INCREMENT PRIMARY KEY,
    ResultID INT NOT NULL,
    FileName VARCHAR(255) NOT NULL,
    FileURL VARCHAR(255) NOT NULL,
    FOREIGN KEY (ResultID) REFERENCES Lab_Result(ResultID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Prescription (
    PrescriptionID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    StaffID INT NOT NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE,
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID) ON DELETE CASCADE
);

-- Module 6: Pharmacy & Finance
CREATE TABLE IF NOT EXISTS Medicine (
    MedicineID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Medicine_Batch (
    BatchID INT AUTO_INCREMENT PRIMARY KEY,
    MedicineID INT NOT NULL,
    ExpiryDate DATE NOT NULL,
    FOREIGN KEY (MedicineID) REFERENCES Medicine(MedicineID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Inventory (
    InventoryID INT AUTO_INCREMENT PRIMARY KEY,
    BatchID INT UNIQUE NOT NULL,
    Quantity INT DEFAULT 0,
    FOREIGN KEY (BatchID) REFERENCES Medicine_Batch(BatchID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Prescription_Item (
    PrescriptionItemID INT AUTO_INCREMENT PRIMARY KEY,
    PrescriptionID INT NOT NULL,
    MedicineID INT NOT NULL,
    Dosage VARCHAR(100) NOT NULL,
    FOREIGN KEY (PrescriptionID) REFERENCES Prescription(PrescriptionID) ON DELETE CASCADE,
    FOREIGN KEY (MedicineID) REFERENCES Medicine(MedicineID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Invoice (
    InvoiceID INT AUTO_INCREMENT PRIMARY KEY,
    VisitID INT NOT NULL,
    TotalAmount DECIMAL(10, 2) DEFAULT 0.00,
    Status ENUM('Pending', 'Paid', 'Partially Paid') DEFAULT 'Pending',
    FOREIGN KEY (VisitID) REFERENCES Visit(VisitID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Invoice_Item (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    InvoiceID INT NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (InvoiceID) REFERENCES Invoice(InvoiceID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Payment (
    PaymentID INT AUTO_INCREMENT PRIMARY KEY,
    InvoiceID INT NOT NULL,
    AmountPaid DECIMAL(10, 2) NOT NULL,
    PaymentMethod ENUM('Cash', 'Card', 'Insurance') DEFAULT 'Cash',
    PaymentDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (InvoiceID) REFERENCES Invoice(InvoiceID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Insurance_Provider (
    ProviderID INT AUTO_INCREMENT PRIMARY KEY,
    ProviderName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Insurance_Claim (
    ClaimID INT AUTO_INCREMENT PRIMARY KEY,
    InvoiceID INT NOT NULL,
    ProviderID INT NOT NULL,
    ClaimAmount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (InvoiceID) REFERENCES Invoice(InvoiceID) ON DELETE CASCADE,
    FOREIGN KEY (ProviderID) REFERENCES Insurance_Provider(ProviderID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Claim_Status (
    StatusID INT AUTO_INCREMENT PRIMARY KEY,
    ClaimID INT NOT NULL,
    Status VARCHAR(50) NOT NULL,
    Notes TEXT,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClaimID) REFERENCES Insurance_Claim(ClaimID) ON DELETE CASCADE
);
